name: Publish Docker image

on:
  push: 
    paths:
      - 'Dockerfile'
      - 'files/**'
      - 'lambda/**'

jobs:

  push_to_registry:

    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: cahik/ecr-lambda-r:v1
  
  test-lambda-functions:

    name: Test lambda functions

    runs-on: ubuntu-latest

    steps:

      - name: Run container
        run: docker run -d -p 9000:8080 --name lambda-r cahik/ecr-lambda-r:v1
      
      - name: Test call
        run: |
          curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"x": 1}'

      - name: Test call
        run: |
          curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"x": "a"}'
      
      - name: Stop container
        run: docker stop lambda-r