name: Test Docker image

on:
  push

jobs:
  
  test-lambda-functions:

    name: Test lambda functions

    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Pull container
        run: docker pull cahik/ecr-lambda-r:v1

      - name: Run container
        run: docker run -d -p 9000:8080 --name lambda-r cahik/ecr-lambda-r:v1
      
      - name: Run Python Tests
        run: |
          pytest python_tests/test_lambda_test.py

      - name: Stop container
        run: docker stop lambda-r
